apiVersion: v2
name: roads-connector
description: |
    Pulls tables' schema and data from a source database and pushes the information to a RabbitMQ message broker.
type: application
kubeVersion: ">=1.21.0"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
# Set to 0.0.0-dev as the version and appVersion is set when building the chart.
version: 0.0.0-dev

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# Set to main for the default branch as the version and appVersion is set when building the chart.
appVersion: "main"
