name: 'Installs prerequisites'
inputs:
  helm-version:
    description: 'Which Helm version to install'
    required: false
    default: 'v4.1.1'
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v5.0.0
      with:
        version: ${{ inputs.helm-version }}
