services:
  app:
    image: roads-synchronizer
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - path: .env.defaults
        required: true
      - path: .env
        required: false
    volumes:
      - .:/app
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      # Default user is "sa".
      MSSQL_SA_PASSWORD: this.key.is.unsecure.and.should.be.only.used.in.development.Ahsh1shuchue
    volumes:
      - database:/var/opt/mssql
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:4.2.4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database:
  rabbitmq:
